version: '3.9'

services:

  backend:
    image: node:alpine
    container_name: nest-backend
    entrypoint: /srv/app/devrun.sh
    ports:
      - '3000:3000'
    volumes:
      - ./tallos-backend:/srv/app
    tty: true 

  frontend:
    image: node:alpine
    container_name: vite-frontend
    entrypoint: /srv/app/devrun.sh
    ports:
      - '3333:3333'
    working_dir: /srv/app
    volumes:
      - ./tallos-vue:/srv/app
    tty: true 